---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
---
Paula (Pinyi) Wu <br>
Email: pw2551@cumc.columbia.edu
<br><br>

## EDUCATION

**Columbia University** <br>
*New York, NY; Class of 2023* <br>
Candidates for Master of Science in Biostatistics

**University of Rochester** <br>
*Rochester, NY; Class of 2021* <br>
Bachelor of Science in Brain & Cognitive Science, Bachelor of Arts in Data Science <br>
Minor in Psychology <br>
<ul>
<li>GPA: 3.99/4.0 </li>
<li>Honors: Summa Cum Laude, Dean scholarship, Dean’s list </li>
</ul>
<br>

## RESEARCH EXPERIENCE
**Adam Snyder lab at University of Rochester** <br>
*Rochester, NY; Research Assistant* <br>
Feb. 2020 – May 2021
<ul>
<li>Assisting in research focusing on decoding EEG signals of novel detections of different kinds of visual components in macaques. Helping analyze EEG data using Python and MATLAB, chairing macaques, preparing experiments setups, providing entertainment and foods to macaques.</li>
</ul>

**Xiongjie Yu lab at Zhejiang University** <br>
*Hangzhou, China; Research Assistant* <br>
Jul. 2019 – Aug. 2019
<ul>
<li>Trained a rat to perform discrimination task on time intervals between a pair of sound stimulus, coded in Spike 2 and MATLAB for experimental protocols and data analysis. </li>
<li>Assisted in novelty detection in sound frequency in nonhuman primates, examining neural activity using electrophysiology (EP) </li>
</ul>
<br>

## TEACHING EXPERIENCE
**Teaching Assistant** <br>
**Rochester, NY**<br>
*Lab Teaching Assistant for CSC 161: Intro to Programming* <br>
Sept. 2020 – May. 2021
<ul>
<li>Held bi-weekly lab sessions, answered Python-related questions, offered coding help and
instructions regarding weekly assignments and a 3-staged project based on different Python topics, graded lab assignments, projects, midterm, and final exam.
</li>
</ul>
*Teaching Assistant for BCS 204: Lab in Cognitive Neuroscience*<br>
Sept. 2020 – Dec. 2020
<ul>
<li>Holding weekly office hour, offering instructions on analysis of behavioral, EEG, fMRI data using Excel,EEGLAB, and SPM12, assisting in recording EEG demo in the actual laboratory setting.</li>
</ul>
**Center for Excellence in Teaching and Learning**<br>
**Rochester, NY**<br>
*Tutor for multiple subjects*<br>
Feb. 2019 – May 2021
<ul>
<li>Tutoring peer students on a one-on-one basis in various subjects, including Brain and Cognitive Science, Biology, and Computer Science. Answering questions regarding course materials, making test preparation plans, and advising overall study skills in specific subjects.</li>
</ul>
<br>

## SKILLS
<ul>
<li>Programming language: Python, Java, R Studio, Excel, MATLAB, Spike 2, SAS; operating Linux, Mac, Windows system</li>
<li>Laboratory skills: brain perfusion fixation, brain dissection of mice, mice behavior training</li>
<li>Excellent communication skills proven by multiple teaching assistant jobs</li>
<li>Foreign languages: native speaker of Mandarin, Japanese N2, intermediate learner of Spanish</li>
</ul>

<br>
<p>You can also download my full Curriculum Vitae <a href="./images/cv_pw.pdf">here</a>.</p>



Back to the [homepage](index.html)